Removed "..." references to avoid "Unexpected token" errors
$ bin/applesign.js -h
/Users/<user>/node-applesign/session.js:440
        groups.push(...newGroups);
                    ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/<user>/node-applesign/index.js:5:26)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)